#!/usr/bin/env bash

set -e

DOCKER_REPO=${DOCKER_USERNAME}/aira2

DOCKER_USERNAME=${DOCKER_USERNAME}
DOCKER_PASSWORD=${DOCKER_PASSWORD}

VERSION=$TRAVIS_JOB_NUMBER
REVISION=$TRAVIS_COMMIT

docker build -f Dockerfile -t $DOCKER_REPO:$REVISION .
docker tag $DOCKER_REPO:$REVISION $DOCKER_REPO:latest
docker tag $DOCKER_REPO:$REVISION $DOCKER_REPO:1.$VERSION

docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

docker push $DOCKER_REPO

docker logout
